# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


 [[main]]
  name = "Αρχική"
  url = "#about"
  weight = 10

[[main]]
  name = "Δημοσιεύσεις"
  url = "#publications"
  weight = 20
  
  [[main]]
  name = "Εισηγήσεις σε Συνέδρια"
  url = "#talks"
  weight = 30


[[main]]
  name = "Featured podcasts"
  url = "#featured"
  weight = 40

  
  [[main]]
  name = "Διδασκαλία"
  url = "#teaching"
  weight = 50
  
[[main]]
  name = "Χρήσιμοι Σύνδεσμοι"
  url = "#resources"
  weight = 60

[[main]]
  name = "Επικοινωνία"
  url = "#contact"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
