[build]
  command = "curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_Linux-64bit.tar.gz | tar xz && ./hugo"
  publish = "public"

[build.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
